### ISSUE TITLE
Clean up image reference so you don't have to repeat so much

### ISSUE THREAD

**Issue by fishcharlie** [thayer11/Project-1#1]
"images/unnamed.png" is repeated a lot when defining the cards. Implementing that into the actual object so you don't have to repeat that code. This would allow it to be much easier if you wish to change the image down the road instead of having to change for each card you only have to change it once.

**Comment by jpbarela** [comment]
Can you write a function to make the url definition easier? If you can write that function that would automatically create the cardarray?
