### ISSUE TITLE
When load no board images

### ISSUE THREAD

**Issue by fishcharlie** [thayer11/Project-1#4]
When you first load/refresh page there is no board icons (see first image). After clicking on two tiles they will reset after a certain amount of time and actually load the back image (see second image).

<img width="1264" alt="image1" src="https://cloud.githubusercontent.com/assets/860375/16532324/8dcb9e2a-3f8e-11e6-8d23-86826043b031.png">

<img width="1257" alt="screen shot 2016-07-01 at 1 21 50 pm" src="https://cloud.githubusercontent.com/assets/860375/16532363/cc453a3a-3f8e-11e6-8a79-26698b6d019a.png">

**Comment by thayer11** [comment]
I added functionality to the Start button so that all back images show signifying start of game. I plan on adding other "decks" with different front and back images so it didn't make sense to have them onload.

**Comment by jpbarela** [comment]
It looks like it turns over only on "Start Over" not start.
